### ISSUE TITLE
Attach screenshots

### ISSUE THREAD

**Issue by marcelmaatkamp** [danielguerra69/metar-weather#1]
This project needs screenshots!!

![3](https://cloud.githubusercontent.com/assets/6911/24827033/84b7c9e8-1c43-11e7-9b57-f1f69ab45aea.png)
![2](https://cloud.githubusercontent.com/assets/6911/24827032/84b78046-1c43-11e7-8cff-50f1c6d14c23.png)
![1](https://cloud.githubusercontent.com/assets/6911/24827031/84b69082-1c43-11e7-8e9c-50346aca8b64.png)

**Comment by danielguerra69** [comment]
Beter late than never
